name: p2p_data_transfer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  device_info_plus: ^11.5.0
  google_api_availability: ^5.0.1
  package_info_plus: ^8.3.1
  flutter_reactive_ble: ^5.4.0
  flutter_ble_peripheral: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
